[package]
name = "wasm-benchmark"
version = "0.1.0"
authors = ["natrixaeria <janng@gmx.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
wasm-bindgen = "0.2"
