[package]
name = "wasm-benchmark"
version = "0.1.0"
authors = ["natrixaeria <janng@gmx.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = { version="0.3", features=["futures_0_3"] }
js-sys = "0.3"

[dependencies.web-sys]
version = "0.3.22"
features = [
    "Window",
    "console"
]
